import argparse
import datetime
import os
import cv2
import json
import uuid
from pathlib import Path
from PIL import Image, ImageOps

SRC = Path(r"D:\OneDrive\mer")
OUT = Path(r"D:\material_wedding")
MANIFEST_OUT = Path("public/wedding_manifest.json")

SECTIONS = ["А якщо", "Разом", "Любити", "Життя", "По справжньому", "Радіти", "Мріяти"]
SECTION_ID_MAP = {
    "А якщо": "ayakscho",
    "Разом": "razom",
    "Любити": "lyubyty",
    "Життя": "zhyttya",
    "По справжньому": "pospravzhnomu",
    "Радіти": "radity",
    "Мріяти": "mriyaty"
}

def process(src: Path = SRC, out: Path = OUT, manifest_out: Path = MANIFEST_OUT):
    out.mkdir(parents=True, exist_ok=True)
    for s in SECTIONS:
        slug = SECTION_ID_MAP[s]
        (out / slug).mkdir(parents=True, exist_ok=True)

    exts = {'.jpg', '.jpeg', '.png', '.webp', '.mp4', '.mov'}
    files = sorted(
        [f for f in src.rglob('*') if f.suffix.lower() in exts],
        key=lambda x: x.stat().st_mtime
    )
    chunk = max(1, len(files) // len(SECTIONS))
    manifest_items = []

    for i, f in enumerate(files):
        sec = SECTIONS[min(i // chunk, len(SECTIONS) - 1)]
        slug = SECTION_ID_MAP[sec]
        is_vid = f.suffix.lower() in {'.mp4', '.mov'}

        if not is_vid:
            name = f"ci_{uuid.uuid4().hex[:8]}.webp"
            try:
                with Image.open(f) as im:
                    im = ImageOps.exif_transpose(im)
                    im = ImageOps.autocontrast(im)
                    im.thumbnail((2048, 2048), Image.LANCZOS)
                    im.save(out / slug / name, "WEBP", quality=82, method=6)
            except Exception as e:
                print(f"[SKIP] {f.name}: {e}")
                continue
        else:
            name = f"ci_{uuid.uuid4().hex[:8]}.mp4"
            try:
                cap = cv2.VideoCapture(str(f))
                fps = cap.get(cv2.CAP_PROP_FPS) or 30
                max_frames = int(fps * 15)
                fourcc = cv2.VideoWriter_fourcc(*'mp4v')
                ret, frame = cap.read()
                if not ret:
                    cap.release()
                    continue
                h, w = frame.shape[:2]
                out_vid = cv2.VideoWriter(str(out / slug / name), fourcc, fps, (w, h))
                count = 0
                while ret and count < max_frames:
                    out_vid.write(frame)
                    ret, frame = cap.read()
                    count += 1
                cap.release()
                out_vid.release()
            except Exception as e:
                print(f"[SKIP] {f.name}: {e}")
                continue

        manifest_items.append({
            "section": sec,
            "slug": slug,
            "file": name,
            "type": "video" if is_vid else "image"
        })
        print(f"[OK] {slug}/{name}")

    manifest = {
        "_version": "1.0.0",
        "_generated": datetime.datetime.utcnow().isoformat() + "Z",
        "_comment": "Generated by scripts/processor.py — do not edit manually",
        "sections": SECTIONS,
        "items": manifest_items
    }

    manifest_out.parent.mkdir(parents=True, exist_ok=True)
    with open(manifest_out, "w", encoding="utf-8") as mf:
        json.dump(manifest, mf, indent=2, ensure_ascii=False)

    print(f"\n[DONE] {len(manifest_items)} items → {manifest_out}")


def parse_args():
    parser = argparse.ArgumentParser(
        description="Simple media processor for the interactive-wedding project."
    )
    parser.add_argument("--input", "-i", default=SRC, type=Path,
                        help=f"Path to raw media directory (default: {SRC}).")
    parser.add_argument("--output", "-o", default=OUT, type=Path,
                        help=f"Path to processed media output directory (default: {OUT}).")
    parser.add_argument("--manifest", "-m", default=MANIFEST_OUT, type=Path,
                        help=f"Path for the manifest JSON file (default: {MANIFEST_OUT}).")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    process(src=args.input, out=args.output, manifest_out=args.manifest)
